# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution
#' @param sigma the standard deviation of Normal 
#' @param x0 The initial value
#' @param N Generate N random numbers 
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' cM(0.05,25,5000)
#' }
#' @export
cM <- function(sigma = 0.05, x0 = 25, N = 5000L) {
    .Call('_StatComp20010_cM', PACKAGE = 'StatComp20010', sigma, x0, N)
}

